import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drunkiel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="{styles.title}">Welcome to my site</h1>

        <p className="{styles.description}">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit
          beatae sit enim! Molestiae eius quasi velit. Incidunt voluptas quos,
          iure recusandae earum tempora non vitae optio facere fugiat dolor
          voluptates. Lorem ipsum dolor, sit amet consectetur adipisicing elit.
          Temporibus voluptates quis in explicabo deleniti exercitationem ab
          voluptatibus placeat, nesciunt architecto laboriosam sequi esse error
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit
          maiores accusantium cumque dolor similique molestiae dolorum debitis?
          Omnis maxime fugit aperiam, repellendus voluptatem quidem laudantium
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit
          beatae sit enim! Molestiae eius quasi velit. Incidunt voluptas quos,
          iure recusandae earum tempora non vitae optio facere fugiat dolor
          voluptates. Lorem ipsum dolor, sit amet consectetur adipisicing elit.
          Temporibus voluptates quis in explicabo deleniti exercitationem ab
          voluptatibus placeat, nesciunt architecto laboriosam sequi esse error
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit
          maiores accusantium cumque dolor similique molestiae dolorum debitis?
          Omnis maxime fugit aperiam, repellendus voluptatem quidem laudantium
        </p>

        <div className="{styles.grid}">
          <div className="{styles.card}">
            <Image src="/Img.jpg" alt="Vercel Logo" width={200} height={300} />
          </div>
        </div>

        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
