import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Mainpage from "../Components/mainpage";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drunkiel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mainpage />
    </div>
  );
};

export default Home;
